"""Generate src/main/state_table.inl from state_model.toml.

Usage: python gen_state_table.py <state_model.toml> <out.inl>

Emits (consumed by src/main/game_state.cpp after it defines RsPredicate/RsState):
  g_state_predicates[]   - flat predicate pool
  g_state_force_params[] - flat int32 param pool (order per SLOT_PARAM_ORDER)
  g_state_reachable[]    - flat const char* pool of reachable_from ids
  g_state_table[]        - one RsState row per state
  RS_STATE_COUNT
"""
import sys
from state_model import load_model, validate

SLOTS = {"boot_level": "RS_SLOT_BOOT_LEVEL", "menu_screen": "RS_SLOT_MENU_SCREEN", "demo": "RS_SLOT_DEMO"}
SLOT_PARAM_ORDER = {"boot_level": ["level", "craft"], "menu_screen": ["screen"], "demo": ["demo"]}
OP = {"eq": "RS_OP_EQ", "ne": "RS_OP_NE", "range": "RS_OP_RANGE", "flag": "RS_OP_FLAG"}


def _cstr(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def gen_state_table(model):
    errs = validate(model)
    if errs:
        raise SystemExit("descriptor invalid:\n  " + "\n  ".join(errs))
    idx = {s.id: i for i, s in enumerate(model.states)}
    preds, fps, rf, rows = [], [], [], []
    for s in model.states:
        pred_off = len(preds)
        for p in s.classify:
            vhi = p.value_hi if p.value_hi is not None else 0
            preds.append(f"  {{ 0x{p.addr:08X}u, 0x{p.mask:08X}u, {OP[p.op]}, "
                         f"0x{p.value & 0xFFFFFFFF:08X}u, 0x{vhi & 0xFFFFFFFF:08X}u }},")
        fp_off = len(fps)
        slot = "RS_SLOT_NONE"
        if s.force:
            slot = SLOTS[s.force.slot]
            for key in SLOT_PARAM_ORDER[s.force.slot]:
                fps.append(f"  {int(s.force.params.get(key, -1))},")
        rf_off = len(rf)
        for rid in s.reachable_from:
            rf.append(f"  {_cstr(rid)},")
        parent = idx.get(s.parent, -1)
        rows.append(f"  {{ {_cstr(s.id)}, {_cstr(s.name)}, {parent}, {model.depth(s.id)}, "
                    f"{pred_off}, {len(s.classify)}, {slot}, {fp_off}, {len(fps) - fp_off}, "
                    f"{rf_off}, {len(s.reachable_from)} }},")
    out = ["// GENERATED by tools/state/gen_state_table.py from state_model.toml. Do not edit."]
    out.append("static const RsPredicate g_state_predicates[] = {\n" + ("\n".join(preds) if preds else "  {0,0,0,0,0},") + "\n};")
    out.append("static const int32_t g_state_force_params[] = {\n" + ("\n".join(fps) if fps else "  0,") + "\n};")
    out.append("static const char* const g_state_reachable[] = {\n" + ("\n".join(rf) if rf else "  0,") + "\n};")
    out.append("static const RsState g_state_table[] = {\n" + "\n".join(rows) + "\n};")
    out.append(f"#define RS_STATE_COUNT {len(model.states)}")
    return "\n\n".join(out) + "\n"


if __name__ == "__main__":
    model = load_model(sys.argv[1])
    with open(sys.argv[2], "w", newline="\n") as f:
        f.write(gen_state_table(model))
    print(f"wrote {sys.argv[2]} ({len(model.states)} states)")
